export const SET_USER = "SET_USER";
export const ADD_ACTION_QUEUE = "ADD_ACTION_QUEUE";
export const REMOVE_ACTION_QUEUE = "REMOVE_ACTION_QUEUE";
export const INITIALIZE_CONNECTION = "INITIALIZE_CONNECTION";
